repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: check-ast
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: local
    hooks:
      - id: local-uv-sync
        name: uv-sync
        stages: [pre-commit]
        language: system
        entry: uv sync
        pass_filenames: false
      - id: local-uv-lock
        stages: [pre-commit]
        name: uv lock
        language: system
        entry: uv lock --frozen
        pass_filenames: false
      - id: local-uv-compile
        name: uv-compile-main
        stages: [pre-commit]
        language: system
        entry: uv pip compile --universal --quiet --output-file requirements.txt pyproject.toml
        pass_filenames: false
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: ["--config", "pyproject.toml"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.2"
    hooks:
      - id: mypy
        args: ["--config-file=./pyproject.toml"]
